/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('antdv-next')['Anchor']
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AFlex: typeof import('antdv-next')['Flex']
    AMenu: typeof import('antdv-next')['Menu']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioButton: typeof import('antdv-next')['RadioButton']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATypography: typeof import('antdv-next')['Typography']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAnchor: typeof import('antdv-next')['Anchor']
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AFlex: typeof import('antdv-next')['Flex']
  const AMenu: typeof import('antdv-next')['Menu']
  const ARadio: typeof import('antdv-next')['Radio']
  const ARadioButton: typeof import('antdv-next')['RadioButton']
  const ARadioGroup: typeof import('antdv-next')['RadioGroup']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ATabPane: typeof import('antdv-next')['TabPane']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const ATypography: typeof import('antdv-next')['Typography']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}